### PR TITLE
feat: support verbatimModuleSyntax for renderers-js

### PR DESCRIPTION
**Pull request by lithdew**
Prefix type-only imports with 'type' for renderers-js so that generated code is compliant with the 'verbatimModuleSyntax' option.

### CODE REVIEW

**Comment by lithdew** [comment]
All tests are passing on my side, and the E2E test generated output is compliant with "verbatimModuleSyntax". tsconfig.json for E2E tests includes `"verbatimModuleSyntax": true`.

image

**Review by lorisleiva — APPROVED** [review]
Amazing work, thank you! Would you mind just running `pnpm lint:fix` so CI passes? 🙏

**Comment by lithdew** [comment]
👍 Ran prettier lint and added a patch changeset for `renderers-js`.

**Review by lorisleiva — APPROVED** [review]
Thanks!

**Pull request merged**
